import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { Button } from "@moai/core";
import SlideBar from "../src/components/slidebar";

const Home: NextPage = () => {
  const [isShow, setShow] = useState<boolean>(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SlideBar postion="right" isShow={isShow} child="this is sample text" />
      <div className="flex min-h-screen justify-center items-center">
        <div className="bg-yellow-500">
          <Button onClick={() => setShow(!isShow)}>Click me</Button>
        </div>
        <div className="max-w-xs rounded overflow-hidden shadow-lg my-2">
          <img
            className="w-full"
            src="https://tailwindcss.com/img/card-top.jpg"
            alt="Sunset in the mountains"
          />
          <div className="px-6 py-4">
            <div className="font-bold text-xl mb-2">Next + Tailwind ❤️</div>
            <p className="text-grey-darker text-base">
              Next and Tailwind CSS are a match made in heaven, check out this
              article on{" "}
            </p>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
